# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Nutzungsbasierte Bezahlung (004f8587-b1ea-4229-b41d-7a08f291c40c)'
    appType: 'webApp'
    WebAppName: 'ahhess-azure-devops-toh'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'